version: 2
sources:
  - name: staging
    database: final-project-zoomcamp-2024
    schema: dbt_dwh
    tables:
        - name: dwh_days

models:
  - name: stg_commits
    description: >
      GitHub commits
